### ISSUE TITLE
fix score mismatch between live game play and game replay

### ISSUE THREAD

**Issue by 0xRampey** [stackrlabs/comets#11]
- [x] Make sure all ticks from start to end of game are being recorded
- [ ] feed recorded ticks back into live gameplay to make sure that they are not the problem. Also doubles as a test.
- [x] Simplify game dynamics to remove any source of stochasticity
- [x] Make sure `render()` is not performing any game logic (since we only run `update()` inside STF)
- [x] Remove randomness from explosion

Worst case
- [ ] Run even `render()` inside the STF with a virtual DOM

**Comment by aashutoshrathi** [comment]
Fixed in https://github.com/stackrlabs/comets/commit/2ca86c8616231e776cdfd5615e3681c730edd79c
